[package]
name = "midi"
version = "1.0.0"
authors = ["Dan <dansonlinepresence@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dlal-component-base = { path = "../base" }
midir = "0.5.0"
multiqueue2 = "0.1.6"
