import dlal

audio=dlal.Component('audio')
fm1=dlal.Component('fm')
fm2=dlal.Component('fm')
midi=dlal.Component('midi')
sfml=dlal.Component('sfml')
buf=dlal.Component('buffer')
audio.command('set 22050 6')
buf.command('resize 64')
fm1.connect(audio)
fm2.connect(audio)
midi.connect(fm1)
sfml.connect(fm2)
audio.connect(buf)
buf.connect(audio)
sfml.add()
midi.add()
audio.add()
fm1.add()
fm2.add()
audio.command('start')

raw_input()
