[package]
name = "stft"
version = "1.0.0"
authors = ["Dan <dansonlinepresence@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dlal-component-base = { path = "../base" }
rustfft = "6.0.0"
