os:
  - linux
  - osx
dist: trusty
sudo: required
addons:
  apt:
    update: true
install:
  - python3 go.py --setup --python python3
  - export PATH=/usr/local/bin:$PATH
script: sudo python3 go.py --build --build-update-submodules --test "*" --python python3
notifications:
  email: false
