os:
  - linux
  - osx
dist: trusty
sudo: required
addons:
  apt:
    update: true
install:
  - python go.py --setup
  - export PATH=/usr/local/bin:$PATH
script: sudo python go.py -b -t "*"
notifications:
  email: false
