[package]
name = "dlal-component-macro"
version = "1.0.0"
authors = ["Dan <dansonlinepresence@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
handlebars = "3.5.0"
serde_json = "1.0.48"
