[package]
name = "iir"
version = "1.0.0"
authors = ["Dan <dansonlinepresence@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
dlal-component-base = { path = "../base" }
num-complex = "0.3"
polynomials = "0.2.3"
