[package]
name = "noisebank"
version = "1.0.0"
authors = ["Dan <dansonlinepresence@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
dlal-component-base = { path = "../base" }
rand = "0.8.3"
rustfft = "6.0.0"
