[package]
name = "dlal-component-base"
version = "1.0.0"
authors = ["Dan <dansonlinepresence@gmail.com>"]
edition = "2018"

[dependencies]
dlal-component-macro = { path = "macro" }
serde_json = "1.0.115"
