[package]
name = "afr"
version = "1.0.0"
authors = ["Dan <dansonlinepresence@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dlal-component-base = { path = "../base" }
claxon = "0.4.3"
hound = "3.5.1"
