[package]
name = "midman"
version = "1.0.0"
authors = ["Dan <dansonlinepresence@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dlal-component-base = { path = "../base" }
lazy_static = "1.4.0"
regex = "1.3.7"
serde = { version = "1.0.106", features = ["derive"] }
